[project]
name = "jac-playground"
version = "1.0.0"
description = "Jac client application: jac-playground"
entry-point = "main.jac"

[dependencies]

[dependencies.npm]
jac-client-node = "1.0.5"
"@monaco-editor/react" = "^4.7.0"
"@tailwindcss/vite" = "^4.1.17"
clsx = "^2.1.1"
lucide-react = "^0.555.0"
monaco-editor = "^0.55.1"
monaco-editor-textmate = "^4.0.0"
monaco-textmate = "^3.0.1"
react-graph-vis = "^1.0.7"
tailwind-merge = "^3.4.0"
tailwindcss = "^4.1.17"
vis-data = "^8.0.3"
vis-network = "^10.0.2"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "2.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]

[plugins.client.vite]
plugins = ["tailwindcss()"]
lib_imports = ["import tailwindcss from '@tailwindcss/vite'"]

[environments.response.headers]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[jacpack]
name = "jacPlayground"
description = "Official Jac Playground"
jaclang = "0.9.14"

[[jacpack.plugins]]
name = "jac-client"
version = "0.2.14"