[project]
name = "jac-playground"
version = "1.0.0"
description = "Jac client application: jac-playground"
entry-point = "src/app.jac"

[plugins.client.vite]
plugins = ["tailwindcss()"]
lib_imports = ["import tailwindcss from '@tailwindcss/vite'"]

[dependencies.npm]
"@monaco-editor/react" = "^4.7.0"
"@tailwindcss/vite" = "^4.1.17"
"clsx" = "^2.1.1"
"lucide-react" = "^0.555.0"
"monaco-editor" = "^0.55.1"
"monaco-editor-textmate" = "^4.0.0"
"monaco-textmate" = "^3.0.1"
"react" = "^19.2.0"
"react-dom" = "^19.2.0"
"react-graph-vis" = "^1.0.7"
"react-router-dom" = "^6.30.1"
"tailwind-merge" = "^3.4.0"
"tailwindcss" = "^4.1.17"
"vis-data" = "^8.0.3"
"vis-network" = "^10.0.2"

[environments.response.headers]
"Cross-Origin-Opener-Policy" = "same-origin"
"Cross-Origin-Embedder-Policy" = "require-corp"